package com.gradientspark;

public class Main {

    public static void main(String[] args) {
//        Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
//        the first 10 terms will be:
//
//        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//        By considering the terms in the Fibonacci sequence whose values do not exceed four million,
//        find the sum of the even-valued terms.

        int firstNumber = 0;
        int secondNumber = 1;
        int nextNumber = 0;
        int totalSum = 0;

        while(nextNumber <= 4000000) {
            nextNumber = firstNumber + secondNumber;
            firstNumber = secondNumber;
            secondNumber = nextNumber;

            if(nextNumber % 2 == 0) {
                totalSum = totalSum + nextNumber;
            }
        }

        System.out.println(totalSum);
    }
}
